# Schema documented at https://render.com/docs/yaml-spec
services:
  - type: web
    name: solara
    env: python
    buildCommand: uv sync
    startCommand: gunicorn app:app --worker-class=gthread --threads=4 --timeout=0
    plan: free
    numInstances: 1
    envVars:
      - key: VUE_USERNAME
        generateValue: false
        sync: false
      - key: VUE_PASSWORD
        generateValue: false
        sync: false
      - key: TIMEZONE
        value: America/Los_Angeles
      - key: LOAD_MANAGE_ENABLED
        value: "False"
      - key: LOAD_MANAGE_INTERVAL_SECS
        value: "30"
      - key: LOAD_TARGET_WH
        value: "-50"
